name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: Go fmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go files need formatting"
            gofmt -d .
            exit 1
          fi
      - name: Go test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: go test ./...
      - name: Build Debian package
        run: scripts/build_deb.sh
