name: Publish Debian package

on:
  push:
    branches:
      - main

jobs:
  publish-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install apt-ftparchive
        run: sudo apt-get update && sudo apt-get install -y apt-utils
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: go test ./...
      - name: Publish Debian package
        env:
          DEPLOYMENT_SSH_KEY: ${{ secrets.DEPLOYMENT_SSH_KEY }}
        run: scripts/publish_debian.sh
